
services:
  api:
    build:
      context: .
      dockerfile: ClinicBooking.API/Dockerfile
    image: edris99/clinic-booking-api:latest
    ports:
      - "7180:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=ClinicBookingDb;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;
      - JwtSettings__SecretKey=${JWT_SECRET}
      - JwtSettings__ExpiryMinutes=60
      - AppSettings__BaseUrl=http://localhost:7180
      - AppSettings__ClientBaseUrl=http://localhost:7172
      - Notifications__BaseUrl=http://notifications:8080
    depends_on:
      - db
      - notifications
    restart: on-failure

  notifications:
    build:
      context: .
      dockerfile: ClinicBooking.Notifications/Dockerfile
    image: edris99/clinicbooking-notifications:latest
    environment:
      - Brevo__ApiKey=${BREVO_API_KEY}
      - Brevo__SenderEmail=edriskohestani1010@outlook.com
    depends_on:
      - db

  client:
    build:
      context: .
      dockerfile: ClinicBooking.Client/Dockerfile
    image: edris99/clinicbooking-client:latest
    ports:
      - "7172:8080"

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - mssqldata:/var/opt/mssql

volumes:
  mssqldata:
